### ISSUE TITLE
Manim Editor v0.3.2 do not find css and js files

### ISSUE THREAD

**Issue by clementpoiret** [ManimCommunity/manim_editor#74]
Hi, I am currently trying to replicate the minimal example from the documentation using manim editor 0.3.2.
On Vivaldi or Google Chrome, the page appears to be not formatted as it do not find css and js files as seen below.
The library is installed through a classic pip install.

![image](https://user-images.githubusercontent.com/10899984/142614712-2550037c-e246-4dd8-9d48-3e4f9d9c327c.png)

**Comment by clementpoiret** [comment]
When using manedit quick export with CLI it doesn't find */static/webpack, it's normal because the static folder contains only the img folder. The same thing happen on 0.3.1. 
v0.3.0 works fine though

**Comment by christopher-besch** [comment]
Ups...
When I created the last release, I forgot to compile. I've published v0.3.3, which works.

Thanks a lot!

**Comment by clementpoiret** [comment]
If only bugs were always so simple to resolve :+1: 
Everything works fine now, thanks! :100:
