### ISSUE TITLE
Manedit v0.3.3 don't take priority into account

### ISSUE THREAD

**Issue by clementpoiret** [ManimCommunity/manim_editor#75]
Hey, I'm trying to make a presentation comprising 7 classes.
After the generation using `manim --save_sections hsf.py`, they are order by default in alphabetic order in manedit.
Unfortunately, it's not the correct order so I change the priority in manedit, but it doesn't seem to be taken into account as the final order stays in alphabetic order during the presentation.

EDIT: it'll be easier with my presentation. Here it is: https://github.com/clementpoiret/manim_hsf
Sorry for bad coding quality, I'm mainly exploring manim + manedit :+1: 
The order should be: 

1/ Introduction
2/ State of Need
3/ Preprocessing
4/ Segmentation
5/ BaggingTta
6/ Postprocessing
7/ PreliminaryResults

**Comment by christopher-besch** [comment]
For some reason `--write_all` didn't work for me but I managed to reproduce the error. I'm fixing it.

**Comment by christopher-besch** [comment]
I think I've fixed it. Could you take a look at [this](https://christopher-besch.github.io/christopher-besch/test/index.html). Is it supposed to look like that?

**Comment by clementpoiret** [comment]
Yes, you have it in the correct order now! :+1: 
Amazing reactivity :100:

**Comment by christopher-besch** [comment]
Thank you very much for your top-notch problem description. It's really a joy to work with that!

PS: I'll bump the version now.
