### ISSUE TITLE
Manedit don't detect projects although the directory exists

### ISSUE THREAD

**Issue by clementpoiret** [ManimCommunity/manim_editor#76]
Hey, it's me again, sorry for opening so many issues in such a shot period of time!
I'm still working on the same project, but this time I updated to manedit 0.3.4.

Unlike v0.3.3, it doesn't find created projects in the main "Project Selection" page, but detects that a project already exists when we want to create a project with the same name.

Steps to reproduce:

* Code a project,
* `manim --save_sections hsf.py`,
* In manedit v0.3.4: create a project named for example `HSF`,
* Once the project is populated, you end up in the Project Selection page. On v0.3.3 you see `HSF`, but v0.3.4 says `No project was found in the CWD; you can change the CWD or create a new project.`, (the directory `HSF` exists in the CWD),
* Go to `create new project`, name it `HSF`, you get: `The project name 'HSF' points to a filled directory. If this is a project, you can open it instead.`

**Comment by christopher-besch** [comment]
I'll look at it, but I might not finish it today.

**Comment by christopher-besch** [comment]
I failed to replicate the problem, I ran `manim --save_sections hsf.py Segmentation` and then `manim_editor` in the same directory. In the Manim Editor I selected `create a  new project`, called it `HSF`, selected the `Segmentation` scene and confirmed.
Then I get to see this:
![image](https://user-images.githubusercontent.com/57909184/142775994-945f5da2-aace-4919-a7b4-648cf5e02bc9.png)

Did you do anything differently?

**Comment by clementpoiret** [comment]
Hmm that's strange.
Here is my full folder after running `manim --save_sections hsf.py`, as you can see, nothing is found by manedit

[HSF.tar.gz](https://github.com/ManimCommunity/manim_editor/files/7579492/HSF.tar.gz)

![2021-11-22 09 57 19 localhost c4db016ee442](https://user-images.githubusercontent.com/10899984/142831853-9a93381c-4064-44e8-a12d-5d93dc148985.png)

**Comment by clementpoiret** [comment]
By exporting only Segmentation (like you did), manedit works as expected, showing the project. I personnaly exported all but `BaseHsf`, and tried to create a project on manedit with either all sections, or only one (in the case I uploaded in previous post, only `preprocessing`)

**Comment by christopher-besch** [comment]
> Hmm that's strange.
> Here is my full folder after running `manim --save_sections hsf.py`, as you can see, nothing is found by manedit
> 
> [HSF.tar.gz](https://github.com/ManimCommunity/manim_editor/files/7579492/HSF.tar.gz)
> 
> ![2021-11-22 09 57 19 localhost c4db016ee442](https://user-images.githubusercontent.com/10899984/142831853-9a93381c-4064-44e8-a12d-5d93dc148985.png)
> 

After rendering with Manim, there shouldn't be any project folders. So this is the expected behaviour.
Or am I misunderstanding something?

PS: I currently can't take a look at the tar.gz I'll do that later today.

**Comment by clementpoiret** [comment]
Oops sorry, I should have been unclear. Yes, I know that manim doesn't create the project, it's created by manedit.
But, when I export only one section using manim (like you did), I can create a project and see it on manedit. So I can replicate what you did.
However, when I export everything with manim (actually all but not the `BaseHsf`), manedit creates the project but I can't see it in the project selection page

**Comment by christopher-besch** [comment]
Copy that.
I'll look into it later today.

**Comment by christopher-besch** [comment]
I managed to reproduce it and fixed it. Could you check `v0.3.5` and see if it's still there?

And don't sorry for opening many issues; this kind of feedback is exactly what I need.
Thanks a lot again!

PS: If you're interested in knowing what caused this: I'm using JSON Schema files to check if a `project.json` really belongs to a Manim Editor project. These schemas contain information on how the different fields in the JSON should look like. You can create these schema files from an example JSON, which I've done. The problem was that the duration of all sections in that example were integers. So the Schema set that as the type for the `duration` parameter. Your example has a float somewhere though so it should refused to load.

**Comment by clementpoiret** [comment]
Amazing! :D
I tried and it works as expected.

Thanks for your reactivity and the explanation!
