### ISSUE TITLE
Problem with exporting the file

### ISSUE THREAD

**Issue by Arkit-Ray** [ManimCommunity/manim_editor#85]
After I press the export presentation button on the localhost webpage, and then run the command 'python3 -m http.server' in the directory, the webpage does not pop up and if I open the server link then it says that the Site cannot be reached. I am requesting for a more guided tutorial/explanation for how to export and view the file.

**Comment by christopher-besch** [comment]
A better tutorial would indeed be helpful.
You have to run the `python3 -m http.server` command inside the project directory (the folder with the name of your project in the current working directory). Then you should be able to open the presented link in your browser.
If that fails, could you send me a screenshot of the content of the project folder?

**Comment by christopher-besch** [comment]
This looks fine, the Manim Editor did it's job. Though the browser can't access the server. This is probably an issue with your `http.server` or some firewall of sorts. Could you send me the terminal output and the error message of the browser, please?

**Comment by Arkit-Ray** [comment]
The browser does not pop up with the site but when I copy past the server it shows the following
![Screenshot (75)](https://user-images.githubusercontent.com/76995622/151285884-1a60a75e-9a44-448e-affb-0ec6fe602fb3.png)
![Screenshot (76)](https://user-images.githubusercontent.com/76995622/151285888-afdda1c0-e9be-4d84-8c0a-84779e2670c5.png)
:

**Comment by naveen521kk** [comment]
Oh use `https://localhost:8000`

**Comment by Arkit-Ray** [comment]
still doesn't work, it shows `::1 - - [27/Jan/2022 10:34:53] code 400, message Bad request version ('localhost\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
::1 - - [27/Jan/2022 10:34:53] "▬♥☺☻ ☺ ☺ü♥♥↓úYØ↕N‼¥"Â&o♦âþóyROöDû£Ê `¼<[ÓãÉú'¹F½®        ³Dæ2©q&!Ç[l♦fÛ  ªª‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶   / 5☺ ☺êê     ♫ ♀       localhost ↨  ÿ☺ ☺  " 400 -
::1 - - [27/Jan/2022 10:34:53] code 400, message Bad request version ('localhost\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
::1 - - [27/Jan/2022 10:34:53] "▬♥☺☻ ☺ ☺ü♥♥♣e{◄↕Â¶¥$×)rê3ú³À↨£ö8Ï►È»!õÑ:o /i◄↕êÖjMsUÍ¦=û9sÁ¨¥ê;/ÊÂÚ>'  zz‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶   / 5☺ ☺→→     ♫ ♀     localhost ↨  ÿ☺ ☺  " 400 -
::1 - - [27/Jan/2022 10:34:53] code 400, message Bad request version ('\x8fÃ/\x11=vG\x99?\x01')
::1 - - [27/Jan/2022 10:34:53] "▬♥☺☻ ☺ ☺ü♥♥Ü× Y{5¶i▲Ã/◄=vG?☺" 400 -
::1 - - [27/Jan/2022 10:34:53] code 400, message Bad request version ('localhost\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
::1 - - [27/Jan/2022 10:34:53] "▬♥☺☻ ☺ ☺ü♥♥æÒÂÙ¬i←▬}íè¡ÜÛ[¤ó#®¶☺õÉê®←Q mDä®+▼!Aw,E°SÎ°▲"~"Q37\&Fî+Ê←  ÊÊ‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶   / 5☺ ☺::     ♫ ♀      localhost ↨  ÿ☺ ☺  " 400 -`

**Comment by Arkit-Ray** [comment]
still not working

**Comment by naveen521kk** [comment]
how about http://0.0.0.0:8000

**Comment by Arkit-Ray** [comment]
No still not working

**Comment by Arkit-Ray** [comment]
nvm, it worked finally, I just had to put in HTTP instead of HTTPS because the local host cannot run a secure connection
