### ISSUE TITLE
 Install manually from git manim_editor

### ISSUE THREAD

**Issue by pihightech** [ManimCommunity/manim_editor#90]
Hello,
I'm a young developer and I can't install the project from the git repo.
Do you have to do 'npm install'
In folder, you have to go to run the command:
python3 -m http.server ?

Thanks in advance

**Comment by christopher-besch** [comment]
You don't need `npm` to install the Manim Editor. Refering to the [installation instructions](https://docs.editor.manim.community/en/stable/installation.html):
Run this after installing Python and Manim.
```bash
python -m pip install manim-editor
```
