### ISSUE TITLE
Issue installing and running the minimal example

### ISSUE THREAD

**Issue by hugorichard** [ManimCommunity/manim_editor#93]
Hi everyone, thanks for your work.
I tried to install manim-editor with pip
I got an error due to mapbox-earcut (due to the requirements, when I install the latest version of mapbox-earcut it works).
Then I tried to install manim-editor from source by cloning the git repo, doing `poetry build `and then `pip install dist/....whl` which worked without issues. 
I then ran the minimal example, generated the scenes with the correct flag.
But launching manim-editor, I don't get any of the images and I cannot click on the "confirm selection" button.
Do you have any ideas of what might be the cause of this issue ?

**Comment by uwezi** [comment]
Be aware that the manim-editor project has last been updated 3 years ago. I would consider this project abandoned. Manim and Python have changed a lot during these past three years.

**Comment by hugorichard** [comment]
Thanks ! Do you know of a maintained tool to make presentations with manim ?

**Comment by uwezi** [comment]
> Thanks ! Do you know of a maintained tool to make presentations with manim ?

Manim-slides also only seems to have one active developer, but it was updated 2 weeks ago and has quite some active users on the ManimCE Discord
https://manim-slides.eertmans.be/latest/

**Comment by hugorichard** [comment]
Thanks I'll close the issue
